# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master", "github-action"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest
          gofumpt -w .
          CHANGES=$(git diff --name-only HEAD --)
          if [ -n "$CHANGES" ] ; then
              echo "There are changes after running gofumpt:"
              echo "$CHANGES"
              git diff
              exit 1
          fi
